swagger: "2.0"
info:
  version: "1.0.0"
  title: "Driver Manager API"
basePath: "/api/v1"
tags:
  - name: "manager"
schemes:
  - "https"
consumes:
  - "application/json"
produces:
  - "application/json"
paths:
  /devices/{device_id}:
    get:
      tags:
        - "device"
      summary: "Get a device"
      operationId: "get_device"
      parameters:
        - name: "device_id"
          in: "path"
          description: "The id of the device to retrieve"
          required: true
          type: "string"
      responses:
        200:
          description: "Successfully retrived device"
          schema:
            $ref: "#/definitions/Device"
        404:
          description: "Device doesn't exist"
      x-swagger-router-controller: "api.web.controllers.devices_controller"
    delete:
      tags:
        - "device"
      summary: "Remove a device"
      operationId: "remove_device"
      parameters:
        - name: "device_id"
          in: "path"
          description: "The id of the device to remove"
          required: true
          type: "string"
      responses:
        202:
          description: "Successfully deleted device"
        404:
          description: "Device doesn't exist"
      x-swagger-router-controller: "api.web.controllers.devices_controller"
    put:
      tags:
        - "device"
      summary: "Update and replace a device"
      operationId: "update_device"
      parameters:
        - name: "device_id"
          in: "path"
          description: "The id of the device to update"
          required: true
          type: "string"
        - name: "Device"
          in: "body"
          required: true
          schema:
            $ref: "#/definitions/Device"
      responses:
        200:
          description: "Successfully updated device"
        404:
          description: "Device doesn't exist"
      x-swagger-router-controller: "api.web.controllers.devices_controller"
  /device:
    get:
      tags:
        - "device"
      summary: "Gets all devices"
      operationId: "get_all_devices"
      responses:
        200:
          description: "Successfully received all devices"
          schema:
            $ref: "#/definitions/Devices"
      x-swagger-router-controller: "api.web.controllers.devices_controller"
    post:
      tags:
        - "device"
      summary: "Add a new device"
      operationId: "add_device"
      parameters:
        - in: "body"
          name: "body"
          description: "Device to add"
          required: true
          schema:
            $ref: "#/definitions/Device"
      responses:
        201:
          description: "Device added"
      x-swagger-router-controller: "api.web.controllers.devices_controller"
definitions:
  Devices:
    type: array
    items:
      $ref: "#/definitions/Device"
  Device:
    type: "object"
    required:
      - "name"
      - "type"
      - "ip"
      - "enable"
    properties:
      id:
        type: "integer"
        format: "int32"
      name:
        type: "string"
      type:
        type: "string"
      ip:
        type: "string"
      enable:
        type: "boolean"
    example:
      id: 1
      name: "Pool"
      type: "ESP32"
      ip: "192.168.10.1"
      enable: true