server:
  port: 8181
  servlet:
    context-path: /manager
  error:
    whitelabel:
      enabled: false

spring:
    profiles:
        active: dev
    main:
        banner-mode: off
        allow-bean-definition-overriding: true
    datasource:
        url: jdbc:mariadb://localhost:3306/fegordomo
        username: fegordomo
        password: fegordomo
        driver-class-name: org.mariadb.jdbc.Driver
    jpa:
        show-sql: true
        open-in-view: false
        hibernate:
            ddl-auto: update
            naming: 
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            dialect: org.hibernate.dialect.MariaDB103Dialect
    quartz:
        job-store-type: jdbc
        properties:
            org:
                quartz:
                    scheduler:
                        instanceId: AUTO
                    threadPool:
                        threadCount: 5
        jdbc:
            initialize-schema: never
    task:
        execution:
            pool:
                max-size: 16
                queue-capacity: 100
                keep-alive: 10s
        scheduling:
            thread-name-prefix: scheduling-
            pool:
                size: 2
    mail:
        host: smtp.gmail.com
        port: 587
        username: fegordomo@fegor.com
        password: ----password----
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true

springdoc:
    api-docs.path: /api-docs
    swagger-ui.path: /swagger-ui-custom.html
    # http://localhost:8181/manager/swagger-ui/index.html?configUrl=/manager/api-docs/swagger-config#

mqtt:
    #url: tcp://localhost:1883
    url: ssl://des1.fegor.com:8883
    username: fegordomo
    password: fegordomo
    client-id: fdc
    default-topic: default
    timeout: 15
    keepalive: 30
    jks-file: C:\codigofuente\fegorsoft\fegordomo\manager\src\main\resources\certs\serverkeystore.jks

fdwm:
    url: http://localhost:4200
